apiVersion: v2
name: external-dns-addon
description: A Helm chart to install and configure external-dns
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
- name: external-dns
  version: "1.14.5"
  repository: "https://kubernetes-sigs.github.io/external-dns/"
