apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: {{ .Release.Namespace }}
spec:
  project: {{ .Values.argo.project }}
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 29.0.1
    helm:
      releaseName: traefik
  destination:
    server: {{ .Values.argo.destination.server }}
    namespace: traefik-{{ .Values.argo.destination.namespaceSuffix }}

