acmeEmail: acme@doge.irish
acmeSolvers:
- dns01:
    route53:
      region: us-east-1
      accessKeyIDSecretRef:
        name: route53-credentials
        key: access-key-id
      secretAccessKeySecretRef:
        name: route53-credentials
        key: secret-access-key
acmeServer: https://acme-v02.api.letsencrypt.org/directory

cert-manager:
  crds:
    enabled: true
