apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  acme:
    email: {{ .Values.acmeEmail }}
    server: {{ .Values.acmeServer }}
    privateKeySecretRef:
      name: le-prod-account-key
    solvers: {{ .Values.acmeSolvers | toYaml | nindent 4 }}

