nameOverride: ""
fullnameOverride: ""

traefik:
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  ports:
    web:
      middleware:
        - traefik-system-http-redirect@kubernetescrd
