nameOverride: ""
fullnameOverride: ""

traefik:
  providers:
    kubernetesIngress:
      publishedService:
        enabled: true
  ports:
    web:
      middlewares:
        - traefik-system-https-redirect@kubernetescrd
